### ISSUE TITLE
nstance.getDepth 提示： {"result":false,"msg":"self signed certificate"}

### ISSUE THREAD

**Issue by abellq** [JCCDex/jcc_rpc#8]
JCC_RPC, 用了instance.getDepth 提示： {"result":false,"msg":"self signed certificate"}
3，4月份的时候可以用的，现在不行了。接口改变了吗？

**Comment by GinMu** [comment]
我问下我们运维人员

**Comment by abellq** [comment]
已经解决了，谢谢！
